### ISSUE TITLE
Installation instructions on README do not work as expected

### ISSUE THREAD

**Issue by hansenp** [RobinsonGroup/robinsongroup.github.io#15]
At least on a Mac M2, the installation instructions don't work as expected. Only after I installing the cairo and pango libraries, executing the following command:

`$ export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib`

and

```
$ pip install badges
$ pip install mkdocs-badges
```

I was able to use the command:

`$ mkdocs serve`

so that the group page was accessible at http://127.0.0.1:8000/.

**Comment by pnrobinson** [comment]
thanks, updated the docs
